### ISSUE TITLE
Duplicate analysis

### ISSUE THREAD

**Issue by BenMinch** [anhd-ha/TIGTOG#1]
Great tool! It works great, but I noticed it sometimes (seemingly randomly) analyzes the same MAG twice and in the final csv file, will give two rows of predictions with these sometimes being slightly different (in the confidence score).

**Comment by anhd-ha** [comment]
@BenMinch Thank you for trying out TIGTOG 👋

We are currently unable to reproduce the issue, could you please send me the input MAGs and the command you used that led to the error?

**Comment by BenMinch** [comment]
I Unfortunately cannot send the MAGS as they are part of an upcoming
publication, but the command was just this: python tigtog.py -i
Clean_partial_bins_99ANI -n partial -t 12
